### PR TITLE
fixed compiler & parser errors

### PR DESCRIPTION
**Pull request by mattes-bru**
Hi @jagreenwood,

first let me thank you for providing this library. 

I tried to use it and noticed some compiler errors on a swift 5.10 project. After the code compiled, there were some missing values which result in errors during the parsing the results from the WeatherKit service. I added the missing values as well. 

You'll find the changes I made to get open-weather-kit running in this pull request.

### CODE REVIEW

**Comment by jagreenwood** [comment]
Hi @mattes-bru Thank you so much for raising this issue and contributing!

One of the goals of this project is to maintain as much of the native WeatherKit API as possible and the edits to `WeatherQuery` have moved away from this goal. 
I think a change could be made to the internal parsing to resolve the issue.
This should also resolve the failing tests.

**Comment by jagreenwood** [comment]
I'm also seeing a reference to a submodule added in the diff. What is that for or was that an accident?

**Comment by mattes-bru** [comment]
The submodule was clearly a mistake. I'll remove it. 

The compiler error I tried to solve is:

WeatherQuery.swift:31:29 Cannot convert value of type 'KeyPath<WeatherProxy, Forecast<MinuteWeather>?>' to expected argument type 'KeyPath<WeatherProxy, Forecast<MinuteWeather>??>'

which happens when I try to compile the main branch.

**Comment by jagreenwood** [comment]
I [refactored](https://github.com/jagreenwood/open-weather-kit/pull/33) the way the payload is processed and resolved the compilation failure.
I'm still interested in merging your decoding fixes if you have time to edit this pr.

**Comment by mattes-bru** [comment]
I'll open another pull request for that. I also made some changes in the language handling, which allows to make an request in another language than the default one.

**Pull request closed without merging**
